// July Moji/Goi - 28 ta
const JM=[
{id:"jm1",k:"膨大",r:"ぼうだい",mn:"ulkan hajm",mj:"量が非常に大きい",u:"膨大な資料を整理する",ex:"膨大なデータ分析に一ヶ月かかった",sim:["莫大-pul uchun","巨大-fizik kattalik"],tip:"莫大=pul, 膨大=hajm/miqdor, 巨大=fizik",cat:"mondai1"},
{id:"jm2",k:"抑制",r:"よくせい",mn:"bostirish, cheklash",mj:"勢いをおさえること",u:"感情を抑制する",ex:"インフレを抑制するため金利を上げた",sim:["制限-tashqi cheklov","制御-texnik boshqarish"],tip:"抑制=ichki kuch bostirish, 制限=tashqaridan cheklov",cat:"mondai1"},
{id:"jm3",k:"貢献",r:"こうけん",mn:"hissa qo'shish",mj:"社会のために力を尽くす",u:"社会に貢献する",ex:"医学の発展に大きく貢献した",sim:["寄与-rasmiy hissa","奉仕-beg'araz xizmat"],tip:"貢献=umumiy, 寄与=ilmiy/rasmiy, 奉仕=bepul",cat:"mondai1"},
{id:"jm4",k:"催促",r:"さいそく",mn:"shoshiltirish",mj:"早くするよう求めること",u:"返事を催促する",ex:"何度催促しても返事がない",sim:["促進-rivojlantirish","督促-rasmiy talab"],tip:"催促=kundalik shoshiltirish, 督促=rasmiy/huquqiy",cat:"mondai1"},
{id:"jm5",k:"遮断",r:"しゃだん",mn:"to'sish, uzish",mj:"さえぎって止めること",u:"電気を遮断する",ex:"事故で道路が完全に遮断された",sim:["遮る-qisman to'sish","切断-fizik kesish"],tip:"遮断=butunlay to'sish, 遮る=qisman, 切断=fizik",cat:"mondai1"},
{id:"jm6",k:"把握",r:"はあく",mn:"to'liq tushunish",mj:"しっかりと理解すること",u:"状況を把握する",ex:"まず状況を把握してから行動しよう",sim:["理解-umumiy tushunish","掌握-nazorat olish"],tip:"把握=chuqur anglash, 理解=umumiy, 掌握=hokimiyat",cat:"mondai1"},
{id:"jm7",k:"簡潔",r:"かんけつ",mn:"qisqa va aniq",mj:"短くて要点がまとまっている",u:"簡潔に説明する",ex:"レポートは簡潔にまとめてください",sim:["明瞭-ravshan","簡単-oson"],tip:"簡潔=qisqa+aniq(matn), 明瞭=tushunarli, 簡単=qiyin emas",cat:"mondai1"},
{id:"jm8",k:"偏見",r:"へんけん",mn:"bir tomonlama noto'g'ri fikr",mj:"かたよった見方",u:"偏見を持たない",ex:"偏見のない社会を目指すべきだ",sim:["先入観-oldindan fikr","差別-kamsitish"],tip:"偏見=noto'g'ri fikr, 先入観=birinchi taassurot, 差別=amaliy",cat:"mondai2"},
{id:"jm9",k:"克服",r:"こくふく",mn:"yengish (qiyinchilikni)",mj:"困難に打ち勝つこと",u:"困難を克服する",ex:"病気を克服して復帰した",sim:["乗り越える-oshib o'tish","打破-buzish"],tip:"克服=ichki qiyinchilik, 乗り越える=to'siq, 打破=tizim",cat:"mondai2"},
{id:"jm10",k:"堅実",r:"けんじつ",mn:"ishonchli, puxta",mj:"しっかりしていて確か",u:"堅実な計画",ex:"堅実な経営で会社を成長させた",sim:["確実-aniq","着実-bosqichma-bosqich"],tip:"堅実=umumiy ishonchli, 確実=natija aniq, 着実=sekin to'g'ri",cat:"mondai2"},
{id:"jm11",k:"摩擦",r:"まさつ",mn:"kelishmovchilik",mj:"対立、こすれ合うこと",u:"貿易摩擦",ex:"隣国との経済摩擦が続いている",sim:["衝突-to'qnashuv","対立-qarama-qarshilik"],tip:"摩擦=asta-sekin ziddiyat, 衝突=keskin, 対立=ikki tomon",cat:"mondai2"},
{id:"jm12",k:"あっさり",r:"あっさり",mn:"kutilganidan oson",mj:"簡単に、さっぱり",u:"あっさり負けを認めた",ex:"難しいと思ったがあっさり解決した",sim:["さっぱり-toza his","すんなり-muammosiz"],tip:"あっさり=kutilganidan oson, さっぱり=toza, すんなり=qarshiliksiz",cat:"mondai3"},
{id:"jm13",k:"ぎっしり",r:"ぎっしり",mn:"zich, to'la-to'kis",mj:"隙間なくいっぱい",u:"予定がぎっしり",ex:"本棚に本がぎっしり並んでいる",sim:["びっしり-zich yozilgan","ぎゅうぎゅう-siqilgan"],tip:"ぎっしり=ichiga to'lgan, びっしり=yuzaga zich, ぎゅうぎゅう=odam",cat:"mondai3"},
{id:"jm14",k:"しぶしぶ",r:"しぶしぶ",mn:"istamay turib, noiloj",mj:"いやいやながら仕方なく",u:"しぶしぶ承知した",ex:"上司に言われしぶしぶ残業した",sim:["いやいや-yoqtirmay","仕方なく-ilojsiz"],tip:"しぶしぶ=ichki qarshilik+bajaradi, 仕方なく=boshqa iloj yo'q",cat:"mondai3"},
{id:"jm15",k:"うっかり",r:"うっかり",mn:"beixtiyor, e'tiborsizlik",mj:"注意が足りなくて失敗",u:"うっかり忘れた",ex:"うっかり電車を乗り過ごした",sim:["つい-iroda yetmay","ぼんやり-xayolchan"],tip:"うっかり=e'tiborsizlik, つい=iroda yetmay, ぼんやり=xayol",cat:"mondai3"},
{id:"jm16",k:"ずらりと",r:"ずらりと",mn:"qator-qator ko'p",mj:"多くのものがきれいに並ぶ",u:"賞状がずらりと並ぶ",ex:"通りにレストランがずらりと並んでいる",sim:["ずらっと-oddiy ko'p qator"],tip:"ずらりと=ta'sirlanarli ko'p, ずらっと=kundalik oddiy",cat:"mondai3"},
{id:"jm17",k:"見込み",r:"みこみ",mn:"ehtimol, kutish",mj:"将来の予想",u:"回復の見込みがある",ex:"今年は売上増加の見込みだ",sim:["見通し-kelajak rasm","予想-bashorat"],tip:"見込み=aniq imkoniyat, 見通し=keng kelajak, 予想=taxmin",cat:"mondai4"},
{id:"jm18",k:"手軽",r:"てがる",mn:"oson, qulay",mj:"簡単にできること",u:"手軽に楽しめる",ex:"このアプリは手軽に使える",sim:["気軽-bemalol","簡単-oddiy"],tip:"手軽=kam mehnat, 気軽=ruhiy yengil, 簡単=qiyin emas",cat:"mondai4"},
{id:"jm19",k:"思い切って",r:"おもいきって",mn:"jasorat bilan",mj:"決心して大胆に行動",u:"思い切って転職した",ex:"思い切って海外に引っ越した",sim:["決心して-qaror","大胆に-jasurona"],tip:"思い切って=qo'rquvni yengib, 決心して=qaror, 大胆に=tabiatdan jasur",cat:"mondai4"},
{id:"jm20",k:"辛うじて",r:"かろうじて",mn:"zo'rg'a, arang",mj:"やっとのことで",u:"辛うじて合格した",ex:"辛うじて最終電車に間に合った",sim:["やっと-axiri","ぎりぎり-chegarada"],tip:"辛うじて=muvaffaqiyatsizlik chegarasida, やっと=uzoq kutib",cat:"mondai5"},
{id:"jm21",k:"妥当",r:"だとう",mn:"to'g'ri, maqbul",mj:"適切で理にかなっている",u:"妥当な判断",ex:"この価格は妥当だと思う",sim:["適切-mos","適当-mos/beparvo"],tip:"妥当=mantiqan to'g'ri, 適切=vaziyatga mos, 適当=ikki ma'no",cat:"mondai5"},
{id:"jm22",k:"素朴",r:"そぼく",mn:"sodda, tabiiy",mj:"飾り気がなく自然",u:"素朴な疑問",ex:"素朴な味わいのパンが人気だ",sim:["純朴-pokiza","質素-kamtar"],tip:"素朴=tabiiy sodda(ijobiy), 純朴=tajribasiz, 質素=kam sarflash",cat:"mondai5"},
{id:"jm23",k:"促す",r:"うながす",mn:"undash, rag'batlantirish",mj:"早くするよう働きかける",u:"注意を促す",ex:"先生は生徒に発言を促した",sim:["催促する-shoshiltirish","奨励する-rag'bat"],tip:"促す=yumshoq undash, 催促する=aniq shoshiltirish",cat:"mondai5"},
{id:"jm24",k:"見直す",r:"みなおす",mn:"qayta ko'rish/baholash",mj:"もう一度見る、評価を改める",u:"計画を見直す",ex:"彼の努力を見て見直した",sim:["見返す-o'ch olish"],tip:"見直す=1)tekshirish 2)yaxshi baholash, 見返す=o'ch",cat:"mondai6"},
{id:"jm25",k:"割り込む",r:"わりこむ",mn:"orasiga kirish",mj:"間に無理に入ること",u:"列に割り込む",ex:"会話に割り込まないでください",sim:["口を挟む-gapga aralashish"],tip:"割り込む=ruxsatsiz(salbiy), 口を挟む=gapga suqilish",cat:"mondai6"},
{id:"jm26",k:"立ち直る",r:"たちなおる",mn:"tiklanmoq",mj:"悪い状態から元に戻る",u:"失敗から立ち直る",ex:"彼は離婚から立ち直った",sim:["回復する-jismoniy","復活する-qayta"],tip:"立ち直る=ruhiy, 回復する=sog'lik, 復活する=butunlay qayta",cat:"mondai6"},
{id:"jm27",k:"裏付ける",r:"うらづける",mn:"tasdiqlash, dalil keltirish",mj:"証拠を示して確かめる",u:"データで裏付ける",ex:"実験が理論を裏付けた",sim:["証明する-isbotlash","立証する-rasmiy"],tip:"裏付ける=qo'shimcha dalil, 証明する=to'liq isbot",cat:"mondai6"},
{id:"jm28",k:"嫌がる",r:"いやがる",mn:"yoqtirmaslik(ochiq)",mj:"いやだと避けようとする",u:"注射を嫌がる",ex:"彼は人前で話すのを嫌がっている",sim:["嫌う-yomon ko'rish","避ける-qochish"],tip:"嫌がる=ochiq ko'rsatish(3-shaxs), 嫌う=ichki his",cat:"mondai6"}
];

// July Bunpo - 18 ta
const JB=[
{id:"jb1",g:"～にしたがって",mn:"...ga qarab o'zgarib",mj:"～と一緒に変化する",st:"動詞辞書形/名詞+にしたがって",ex:"年齢が上がるにしたがって体力が落ちる。",exT:"Yosh oshgani sari kuch kamayadi.",sim:["～につれて-tabiiy o'zgarish","～とともに-parallel"],tip:"にしたがって=rasmiy/qoida, につれて=tabiiy, とともに=parallel",we:[{w:"規則にしたがって行動する",y:"Bu 'qoidaga muvofiq' - boshqa ma'no. に従って=muvofiq"}],cat:"m7"},
{id:"jb2",g:"～に関して",mn:"...haqida (rasmiy)",mj:"～について（硬い）",st:"名詞+に関して/に関する+名詞",ex:"この問題に関して意見を述べたい。",exT:"Bu muammo haqida fikr bildirmoqchiman.",sim:["～について-oddiy haqida","～に対して-...ga nisbatan"],tip:"に関して=rasmiy/yozma, について=kundalik, に対して=yo'nalish",we:[{w:"彼に関して優しい",y:"XATO! Shaxsga munosabat uchun に対して: 彼に対して優しい"}],cat:"m7"},
{id:"jb3",g:"～をきっかけに",mn:"...sababli boshlangan",mj:"～がきっかけとなって",st:"名詞/動詞た形+のをきっかけに",ex:"留学をきっかけに日本語を始めた。",exT:"Chet elda o'qish sababli yapon tilini boshladim.",sim:["～を契機に-rasmiy","～がもとで-salbiy sabab"],tip:"をきっかけに=ijobiy boshlang'ich, を契機に=rasmiy, がもとで=salbiy natija",we:[{w:"風邪をきっかけに入院した",y:"Salbiy natija uchun がもとで yaxshi: 風邪がもとで入院した"}],cat:"m7"},
{id:"jb4",g:"～ものなら",mn:"agar iloji bo'lsa (qiyin)",mj:"もし～できるなら（難しい）",st:"動詞可能形+ものなら",ex:"やり直せるものなら、やり直したい。",exT:"Qaytadan qila olsam, qilardim.",sim:["～ことなら-iloji bo'lsa","～たら-oddiy shart"],tip:"ものなら=deyarli mumkin emas lekin xohlaydi, たら=oddiy shart",we:[{w:"明日雨が降るものなら",y:"XATO! Yomg'ir 'qila olish' emas. Faqat iroda/qobiliyat bilan"}],cat:"m7"},
{id:"jb5",g:"～わけがない",mn:"mutlaqo mumkin emas",mj:"絶対に～ない",st:"普通形/い形/な形な+わけがない",ex:"そんな問題が解けないわけがない。",exT:"Bunday masalani yecha olmaslik mumkin emas.",sim:["～はずがない-mantiqan bo'lmasligi kerak","～わけではない-shunday degani emas"],tip:"わけがない=100%mumkin emas, はずがない=mantiqan, わけではない=qisman inkor",we:[{w:"彼が来ないわけではない",y:"BOSHQA grammatika! わけではない='kelmaydi degani emas'. わけがない='kelishi mumkin emas'"}],cat:"m7"},
{id:"jb6",g:"～てたまらない",mn:"juda...chidab bo'lmaydi",mj:"非常に～で我慢できない",st:"て形/くて/で+たまらない",ex:"暑くてたまらない。",exT:"Juda issiq, chidab bo'lmaydi.",sim:["～てしょうがない-ilojsiz","～てならない-o'zi keladi"],tip:"てたまらない=jismoniy/hissiy chidolmas, てしょうがない=oddiy, てならない=rasmiy",we:[{w:"嬉しくてたまらない vs てならない",y:"Ikkalasi to'g'ri! たまらない=kuchli jismoniy, ならない=rasmiy/yozma"}],cat:"m7"},
{id:"jb7",g:"～どころか",mn:"...qayoqda, aksincha",mj:"～ではなく、それ以上に",st:"普通形/名詞+どころか",ex:"手伝うどころか、邪魔ばかりしている。",exT:"Yordam qayoqda, faqat halaqit beryapti.",sim:["～ばかりか-nafaqat","～のみならず-rasmiy nafaqat"],tip:"どころか=kutilganining AKSI, ばかりか=qo'shimcha, のみならず=rasmiy",we:[],cat:"m8"},
{id:"jb8",g:"～に限って",mn:"aynan ...paytda",mj:"～のときに限り、いつもと違う",st:"名詞+に限って",ex:"急いでいるときに限って電車が遅れる。",exT:"Aynan shoshilayotganda poyezd kechikadi.",sim:["～に限り-rasmiy cheklov","～だけ-faqat"],tip:"に限って=Murphy qonuni(yomon payt), に限り=rasmiy cheklov",we:[{w:"参加は学生に限って無料です",y:"Bu に限り - rasmiy cheklov. に限って=kutilmagan holat"}],cat:"m8"},
{id:"jb9",g:"～ようがない",mn:"iloji yo'q, usul yo'q",mj:"～する方法がない",st:"ます形+ようがない",ex:"連絡先がわからないので連絡しようがない。",exT:"Aloqa ma'lumoti noma'lum, bog'lanib bo'lmaydi.",sim:["～わけにはいかない-ijtimoiy sabab","～かねる-xushmuomala rad"],tip:"ようがない=usul yo'q, わけにはいかない=ijtimoiy, かねる=kibar rad",we:[],cat:"m8"},
{id:"jb10",g:"～に違いない",mn:"aniq shunday, shubhasiz",mj:"きっと～だ",st:"普通形+に違いない",ex:"彼が犯人に違いない。",exT:"U aniq jinoyatchi.",sim:["～はずだ-bo'lishi kerak","～に決まっている-kuchli ishonch"],tip:"に違いない=dalilga asoslangan, はずだ=mantiqan, に決まっている=shaxsiy ishonch",we:[],cat:"m8"},
{id:"jb11",g:"～つつある",mn:"...moqda (jarayon)",mj:"だんだん～している途中",st:"ます形+つつある",ex:"環境問題は改善しつつある。",exT:"Atrof-muhit yaxshilanmoqda.",sim:["～ている-oddiy davom","～最中-ayni payt"],tip:"つつある=rasmiy bosqichma-bosqich O'ZGARISH, ている=oddiy",we:[{w:"ご飯を食べつつある",y:"XATO! つつある=bosqichma-bosqich O'ZGARISH. Ovqat yeyish o'zgarish emas"}],cat:"m8"},
{id:"jb12",g:"～にもかかわらず",mn:"...ga qaramasdan",mj:"～のに、～であるけれども",st:"普通形/である+にもかかわらず",ex:"雨にもかかわらず試合は行われた。",exT:"Yomg'irga qaramasdan o'yin bo'lib o'tdi.",sim:["～のに-oddiy qaramasdan","～にかかわらず-farqi yo'q"],tip:"にもかかわらず='ga QARAMASDAN'(A bo'lsa ham B), にかかわらず='FARQI YO'Q'(A/B farqsiz)",we:[{w:"男女にもかかわらず参加できる",y:"XATO! 'Farqi yo'q'=にかかわらず. にもかかわらず=bir narsaga qaramasdan boshqasi"}],cat:"m9"},
{id:"jb13",g:"～一方で",mn:"bir tomondan..., boshqa tomondan",mj:"～する反面",st:"普通形/である+一方で",ex:"都市は便利な一方で自然が少ない。",exT:"Shahar qulay, boshqa tomondan tabiat kam.",sim:["～反面-aksi tomon"],tip:"一方で=ikki tomon parallel, 反面=aksi. 一方だ=faqat bir yo'nalish(BOSHQA!)",we:[{w:"物価は上がる一方だ",y:"BOSHQA grammatika! 一方だ=faqat oshib bormoqda. 一方で=solishtirish"}],cat:"m9"},
{id:"jb14",g:"～ことから",mn:"...dan kelib chiqib (nom/xulosa)",mj:"～という事実から",st:"普通形/な形な+ことから",ex:"形が星に似ていることから「星草」と名付けられた。",exT:"Yulduzga o'xshagani sababli 'yulduz o't' deb nomlangan.",sim:["～ために-sabab","～ので-sabab"],tip:"ことから=nom berish/xulosa SABABI, ので=oddiy sabab",we:[{w:"雨が降ったことから傘を持っていった",y:"XATO! Oddiy sabab uchun ので/から. ことから=nom/ilmiy xulosa uchun"}],cat:"m9"},
{id:"jb15",g:"～としたら",mn:"agar faraz qilsak",mj:"もし～なら（仮定）",st:"普通形+としたら",ex:"宝くじが当たったとしたら何をしますか。",exT:"Lotereya yutsangiz nima qilardingiz?",sim:["～たら-oddiy shart","～としても-bo'lsa ham"],tip:"としたら=real bo'lmasligi mumkin faraz, たら=oddiy shart",we:[],cat:"m9"},
{id:"jb16",g:"～ものの",mn:"...bo'lsa-da, lekin (afsuslash)",mj:"～けれども期待と違って",st:"た形/い/な+ものの",ex:"買ったものの一度も使っていない。",exT:"Sotib olganman-u bir marta ishlatmaganman.",sim:["～が-lekin","～けれども-ammo"],tip:"ものの=kutilgan natija KELMADI(afsuslash), が=oddiy 'lekin'",we:[{w:"高いものの品質がいい",y:"Bu が/けど bilan oddiy. ものの=KUTILMAGAN, salbiy his kerak"}],cat:"m9"},
{id:"jb17",g:"～かねない",mn:"...bo'lishi mumkin (xavfli)",mj:"～する可能性がある（悪い）",st:"ます形+かねない",ex:"無理をすると病気になりかねない。",exT:"Haddan oshsa kasal bo'lishi mumkin.",sim:["～おそれがある-rasmiy xavf","～かもしれない-neytral"],tip:"かねない=SALBIY imkoniyat(ogohlantirish), おそれがある=rasmiy",we:[{w:"合格しかねない",y:"XATO! かねない faqat SALBIY. Ijobiy uchun かもしれない"}],cat:"m9"},
{id:"jb18",g:"～上で",mn:"...uchun / ...da (shart)",mj:"～するために/する際に",st:"辞書形/名詞の+上で",ex:"契約する上で注意すべき点がある。",exT:"Shartnoma tuzishda diqqat kerak nuqtalar bor.",sim:["～にあたって-muhim payt","～際に-rasmiy paytda"],tip:"辞書形+上で=maqsad/shart, た上で=qilgandan keyin. Ikki ma'no!",we:[{w:"食事をした上で出かけた",y:"Bu た上で='qilgandan KEYIN'. 辞書形+上で='qilish UCHUN'"}],cat:"m9"}
];

// July Dokkai - 6 ta
const JD=[
{id:"jd1",t:"短文-環境問題",p:"近年、プラスチックごみによる海洋汚染が深刻な問題となっている。毎年800万トン以上のプラスチックが海に流れ込み、海洋生物に大きな影響を与えている。各国政府はプラスチック製品の使用削減に取り組んでいるが、問題の解決にはまだ時間がかかりそうだ。消費者一人一人の意識改革も必要不可欠である。",qs:[{q:"この文章の主な内容は？",o:["海洋生物の種類","プラスチック海洋汚染問題","政府の環境政策の成功","消費者の買い物習慣"],c:1,e:"文章全体がプラスチック汚染について",wr:["海洋生物は影響を受ける側で主題ではない","政府は取り組んでいるが'成功'とは書いていない","買い物習慣は直接触れていない"]}],kv:["海洋汚染-okeanni ifloslantirish","深刻-jiddiy","削減-kamaytirish","不可欠-zarur"],cat:"short"},
{id:"jd2",t:"短文-働き方改革",p:"日本では「働き方改革」が進められている。長時間労働の是正、多様で柔軟な働き方の実現、同一労働同一賃金の確保が三本柱とされている。テレワークの導入やフレックスタイム制の拡大により、社員が自分のライフスタイルに合わせて働けるようになってきた。しかし、実際には制度を利用しにくい職場もまだ多い。",qs:[{q:"三本柱に含まれないものは？",o:["長時間労働の是正","テレワークの義務化","柔軟な働き方","同一労働同一賃金"],c:1,e:"テレワークは'導入'されているが三本柱ではなく'義務化'とも書いていない",wr:["文中に三本柱として明記","文中に三本柱として明記","文中に三本柱として明記"]}],kv:["是正-tuzatish","柔軟-egiluvchan","賃金-ish haqi","導入-joriy etish"],cat:"short"},
{id:"jd3",t:"中文-AI技術",p:"人工知能技術の発展は生活を大きく変えつつある。医療分野ではAIによる画像診断が医師の判断を支援し早期発見の精度を高めている。教育分野では理解度に合わせた学習が可能になった。一方でAIの判断がブラックボックス化への懸念や雇用への影響を心配する声もある。技術の恩恵を最大限に活かしつつリスクを抑えるための法整備が求められている。",qs:[{q:"AIの医療での役割は？",o:["手術を自動で行う","画像診断で医師を支援","薬の開発","患者と対話"],c:1,e:"'画像診断が医師の判断を支援し'と明記",wr:["手術自動化は触れていない","薬開発は述べられていない","患者との対話は述べられていない"]},{q:"AIの懸念として挙げられていないのは？",o:["判断が不透明","雇用への影響","AIが人間を超える","法整備の必要性"],c:2,e:"'AIが人間を超える'は本文にない",wr:["'ブラックボックス化'=不透明","'雇用への影響を心配'と書かれている","法整備は対策であり懸念そのものではないが注意"]}],kv:["精度-aniqlik","懸念-xavotir","恩恵-ne'mat","法整備-qonun tayyorlash"],cat:"medium"},
{id:"jd4",t:"中文-食文化",p:"日本の食文化はユネスコ無形文化遺産に登録されている。特徴は素材の味を活かした調理法、栄養バランス、季節感の表現、年中行事との結びつきにある。しかし食の欧米化が進み若い世代の和食離れが見られる。家庭で一汁三菜を作る機会も減少している。伝統を次世代に継承するため学校給食での和食提供や料理教室など取り組みが行われている。",qs:[{q:"日本食の特徴として述べられていないのは？",o:["素材の味を活かす調理法","大量生産による低価格","季節感の表現","年中行事との結びつき"],c:1,e:"大量生産・低価格は文中に触れていない",wr:["文中に特徴として明記","文中に特徴として明記","文中に特徴として明記"]}],kv:["無形文化遺産-nomoddiy meros","継承-avlodlarga o'tkazish","欧米化-g'arblashish"],cat:"medium"},
{id:"jd5",t:"長文-読書の価値",p:"デジタル化が進む中、紙の本を手に取る人が減少している。電子書籍により、いつでも読書ができるようになった反面、深い集中力を持つ習慣が失われつつある。研究では紙の本の方が理解度が高い。「ここまで読んだ」という物理的感覚が記憶の定着を助けるためだ。しかし電子書籍にはキーワード検索や辞書機能など利便性もある。大切なのは形式にこだわるのではなく自分に合った方法で楽しむことではないだろうか。",qs:[{q:"紙の本の理解度が高い理由は？",o:["質感が集中力を高める","物理的感覚が記憶定着を助ける","文字が大きい","めくる動作が脳を刺激"],c:1,e:"'物理的感覚が記憶の定着を助ける'と明記",wr:["質感ではなく'ここまで読んだ'という位置感覚","文字サイズは述べられていない","めくる動作は具体的に述べられていない"]},{q:"筆者が伝えたいことは？",o:["紙が電子より優れている","電子には欠点がある","自分に合った方法で楽しむべき","デジタル化は読書を破壊"],c:2,e:"'自分に合った方法で楽しむこと'=筆者の主張",wr:["両方の長所を述べ紙が優れているとは結論していない","欠点だけでなく利便性も認めている","'破壊'は使っていない。'失われつつある'は穏やか"]}],kv:["定着-mustahkamlanish","利便性-qulaylik","こだわる-yopishmoq"],cat:"long"},
{id:"jd6",t:"情報検索-図書館",p:"市立中央図書館\\n開館:平日9:00～20:00/土日祝9:00～17:00\\n休館:毎週月曜(祝日は翌日)\\n貸出:一般書10冊・CD/DVD3点\\n期間:2週間(延長1回のみ、予約なし時)\\nネット予約:24時間受付\\nグループ学習室:事前予約制(1回2時間)",qs:[{q:"土曜日は何時まで？",o:["20:00","17:00","18:00","21:00"],c:1,e:"'土日祝9:00～17:00'と明記",wr:["20:00は平日","18:00はどこにもない","21:00はどこにもない"]},{q:"延長について正しいのは？",o:["何回でも可","予約なしなら1回可","延長不可","2回まで可"],c:1,e:"'延長1回のみ、予約なしの場合'と明記",wr:["'1回のみ'と制限","延長自体は条件付き可能","'1回のみ'で2回ではない"]}],kv:["貸出-ijaraga berish","延長-uzaytirish","翌日-ertasi kun"],cat:"joho"}
];

// Dec Moji/Goi - 25 ta
const DM=[
{id:"dm1",k:"繁栄",r:"はんえい",mn:"gullab-yashnash",mj:"栄えて発展すること",u:"国が繁栄する",ex:"この地域は貿易で繁栄した",sim:["発展-rivojlanish","隆盛-avjlanish"],tip:"繁栄=uzoq muddatli, 発展=jarayon, 隆盛=eng yuqori nuqta",cat:"m1"},
{id:"dm2",k:"脅威",r:"きょうい",mn:"tahdid, xavf",mj:"恐ろしい存在",u:"安全への脅威",ex:"サイバー攻撃は現代の脅威だ",sim:["危険-xavfli","脅迫-qo'rqitish"],tip:"脅威=mavjud xavf, 危険=umumiy xavf, 脅迫=ataylab qo'rqitish",cat:"m1"},
{id:"dm3",k:"概要",r:"がいよう",mn:"umumiy mazmun",mj:"全体のあらまし",u:"計画の概要を説明する",ex:"まず事業の概要を紹介します",sim:["概略-qisqa xulosa","要約-xulosa"],tip:"概要=umumiy ko'rinish(rasmiy), 要約=uzunni qisqartirish",cat:"m1"},
{id:"dm4",k:"拘束",r:"こうそく",mn:"cheklash, bog'lash",mj:"自由を制限すること",u:"時間に拘束される",ex:"この仕事は拘束時間が長い",sim:["束縛-ruhiy bog'lash","制約-cheklov"],tip:"拘束=jismoniy/vaqt, 束縛=ruhiy/hissiy, 制約=sharoit",cat:"m1"},
{id:"dm5",k:"潤う",r:"うるおう",mn:"namlanmoq, boyimoq",mj:"水分を含む、豊かになる",u:"肌が潤う",ex:"雨で畑が潤った",sim:["湿る-nam bo'lish","豊かになる-boyish"],tip:"潤う=ijobiy namlik/boylik, 湿る=salbiy nam",cat:"m1"},
{id:"dm6",k:"覆す",r:"くつがえす",mn:"ag'darish, qarorni o'zgartirish",mj:"決定を変える",u:"判決を覆す",ex:"新しい証拠が通説を覆した",sim:["逆転-teskari o'zgarish"],tip:"覆す=ataylab o'zgartirish, 逆転=o'z-o'zidan teskari",cat:"m1"},
{id:"dm7",k:"惜しむ",r:"おしむ",mn:"afsuslanmoq, ayamoq",mj:"もったいないと思う",u:"別れを惜しむ",ex:"時間を惜しんで勉強した",sim:["残念-afsuski","勿体ない-isrof"],tip:"惜しむ=qimmatli narsani yo'qotishdan afsus",cat:"m2"},
{id:"dm8",k:"甘える",r:"あまえる",mn:"erkalanmoq, suyanmoq",mj:"相手の好意に頼る",u:"親に甘える",ex:"お言葉に甘えてお願いします",sim:["頼る-tayanmoq","依存-bog'liq"],tip:"甘える=ijobiy suyanish, 頼る=yordam so'rash, 依存=salbiy",cat:"m2"},
{id:"dm9",k:"搾る",r:"しぼる",mn:"siqmoq, qisqartirmoq",mj:"範囲を狭くする",u:"候補を絞る",ex:"レモンを搾ってジュースを作る",sim:["限定-cheklash"],tip:"絞る=tanlab qisqartirish(faol), 限定=chegara belgilash",cat:"m2"},
{id:"dm10",k:"衰退",r:"すいたい",mn:"tanazzul, zaiflashish",mj:"勢いが弱くなること",u:"産業が衰退する",ex:"伝統工芸が衰退しつつある",sim:["没落-qulash"],tip:"衰退=asta-sekin pasayish, 没落=keskin qulash",cat:"m2"},
{id:"dm11",k:"とっくに",r:"とっくに",mn:"allaqachon, ancha oldin",mj:"ずっと前に",u:"とっくに終わった",ex:"彼はとっくに帰ったよ",sim:["すでに-rasmiy","もう-oddiy"],tip:"とっくに=ANCHA oldin(ta'kidli), すでに=rasmiy, もう=oddiy",cat:"m3"},
{id:"dm12",k:"せっせと",r:"せっせと",mn:"tinmay, tirish bilan",mj:"休まず一生懸命に続ける",u:"せっせと働く",ex:"彼女はせっせと料理を作っていた",sim:["こつこつ-sekin tinmay"],tip:"せっせと=tez+tinmay, こつこつ=sekin+uzluksiz",cat:"m3"},
{id:"dm13",k:"のんびり",r:"のんびり",mn:"bemalol, shoshilmasdan",mj:"ゆったりとくつろぐ",u:"のんびり過ごす",ex:"田舎でのんびり暮らしたい",sim:["ゆったり-keng/erkin"],tip:"のんびり=vaqtga shoshmay, ゆったり=jismoniy kenglik",cat:"m3"},
{id:"dm14",k:"ひっそり",r:"ひっそり",mn:"jimgina, sokin",mj:"静かで人目につかない",u:"ひっそりと暮らす",ex:"山の中にひっそりと寺がある",sim:["こっそり-yashirincha"],tip:"ひっそり=tabiatdan sokin(muhit), こっそり=ataylab yashirish",cat:"m3"},
{id:"dm15",k:"見落とす",r:"みおとす",mn:"ko'rmay qoldirish",mj:"見るべきものを見逃す",u:"間違いを見落とす",ex:"書類の間違いを見落としていた",sim:["見逃す-qo'yib yuborish","見過ごす-e'tiborga olmay"],tip:"見落とす=tekshirishda sezmaslik, 見逃す=ko'rib turib qo'yish",cat:"m4"},
{id:"dm16",k:"引き受ける",r:"ひきうける",mn:"zimmasiga olmoq",mj:"責任を持って仕事をする",u:"仕事を引き受ける",ex:"そのプロジェクトを引き受けた",sim:["担当する-javobgar"],tip:"引き受ける=o'z xohishi bilan, 担当する=rasmiy javobgarlik",cat:"m4"},
{id:"dm17",k:"差し引く",r:"さしひく",mn:"ayirmoq, chegirib tashlash",mj:"ある額から引くこと",u:"税金を差し引く",ex:"経費を差し引いた利益は少ない",sim:["控除-rasmiy chegirma"],tip:"差し引く=hisob-kitobda ayirish, 控除=soliq chegirmasi",cat:"m4"},
{id:"dm18",k:"切り替える",r:"きりかえる",mn:"almashtirish",mj:"別のものに変えること",u:"気持ちを切り替える",ex:"話題を切り替えましょう",sim:["変更する-rasmiy o'zgartirish"],tip:"切り替える=tez aniq almashtirish, 変更する=rasmiy",cat:"m4"},
{id:"dm19",k:"厄介",r:"やっかい",mn:"qiyin, muammoli",mj:"面倒で困ること",u:"厄介な問題",ex:"この虫は駆除が厄介だ",sim:["面倒-zahmat"],tip:"厄介=boshqalarga ham zarar, 面倒=o'zi uchun zahmat",cat:"m5"},
{id:"dm20",k:"頑丈",r:"がんじょう",mn:"mustahkam, baquvvat",mj:"丈夫で壊れにくい",u:"頑丈な建物",ex:"この金庫は非常に頑丈だ",sim:["丈夫-pishiq"],tip:"頑丈=jismoniy kuchli/sinmaydigan, 丈夫=umumiy pishiq",cat:"m5"},
{id:"dm21",k:"漠然",r:"ばくぜん",mn:"noaniq, loyqa",mj:"はっきりしないこと",u:"漠然とした不安",ex:"将来について漠然と考えている",sim:["曖昧-noaniq(ataylab)"],tip:"漠然=o'zi tushunolmay, 曖昧=ataylab aniqlashtiramay",cat:"m5"},
{id:"dm22",k:"速やかに",r:"すみやかに",mn:"tezda, darhol",mj:"すぐに早く",u:"速やかに対応する",ex:"問題発生時は速やかに報告してください",sim:["直ちに-shu zahoti"],tip:"速やかに=tez+muammosiz(rasmiy), 直ちに=BIR SONIYA kutmay",cat:"m5"},
{id:"dm23",k:"打ち明ける",r:"うちあける",mn:"ochiq aytish, sir aytish",mj:"秘密を正直に話す",u:"悩みを打ち明ける",ex:"友人に本当の気持ちを打ち明けた",sim:["告白する-sevgi e'tirof"],tip:"打ち明ける=ishonchli odamga sir, 告白する=sevgi/din",cat:"m6"},
{id:"dm24",k:"取り消す",r:"とりけす",mn:"bekor qilish",mj:"決めたことをなくす",u:"予約を取り消す",ex:"発言を取り消してください",sim:["撤回する-rasmiy qaytarish"],tip:"取り消す=oddiy bekor, 撤回する=rasmiy bayonot qaytarish",cat:"m6"},
{id:"dm25",k:"追い込む",r:"おいこむ",mn:"siqib qo'yish",mj:"限界まで押すこと",u:"自分を追い込む",ex:"自分を追い込んで勉強した",sim:["追い詰める-burchakka qisish"],tip:"追い込む=cheklagacha itarish(o'ziga ham), 追い詰める=raqibni",cat:"m6"}
];



// Dec Bunpo - 16 ta
const DB=[
{id:"db1",g:"～てからでないと",mn:"...masdan turib bo'lmaydi",mj:"～しなければ後のことはできない",st:"て形+からでないと＋否定",ex:"申し込んでからでないと参加できません。",exT:"Ro'yxatdan o'tmasdan qatnashib bo'lmaydi.",sim:["～てからでなければ-rasmiy","～ないことには-shartli"],tip:"てからでないと=ketma-ketlik+inkor SHART, ないことには=umumiy shart",we:[{w:"食べてからでないと美味しい",y:"XATO! Keyin INKOR kerak: 食べてからでないと分からない"}],cat:"d7"},
{id:"db2",g:"～を問わず",mn:"...farqi yo'q, ...qatiy nazar",mj:"～に関係なく",st:"名詞+を問わず",ex:"経験を問わず応募できます。",exT:"Tajriba farqi yo'q, ariza topshirish mumkin.",sim:["～にかかわらず-farqsiz","～に関係なく-oddiy"],tip:"を問わず=rasmiy/e'lon, にかかわらず=umumiy farqsiz",we:[{w:"天気を問わず楽しい",y:"His-tuyg'u uchun mos emas. Rasmiy sharoit/shart uchun"}],cat:"d7"},
{id:"db3",g:"～に先立って",mn:"...dan oldin (rasmiy)",mj:"～の前に準備として",st:"名詞/動詞辞書形+に先立って",ex:"開会に先立って挨拶があった。",exT:"Ochilishdan oldin salomlashish bo'ldi.",sim:["～前に-oddiy oldin","～に際して-paytida"],tip:"に先立って=rasmiy TAYYORGARLIK, 前に=oddiy, に際して=paytida",we:[{w:"寝るに先立って歯を磨く",y:"Kundalik ish uchun oddiy 前に: 寝る前に歯を磨く"}],cat:"d7"},
{id:"db4",g:"～をめぐって",mn:"...atrofida (munozara)",mj:"～について議論や争い",st:"名詞+をめぐって",ex:"環境問題をめぐって議論が続いている。",exT:"Ekologiya muammosi atrofida bahs davom etmoqda.",sim:["～について-haqida","～に関して-rasmiy haqida"],tip:"をめぐって=QARAMA-QARSHI fikr/ziddiyat, について=oddiy haqida",we:[{w:"趣味をめぐって話した",y:"Oddiy suhbat uchun について: 趣味について話した"}],cat:"d7"},
{id:"db5",g:"～ざるを得ない",mn:"...masdan iloji yo'q",mj:"～しないわけにはいかない",st:"ない形(ない→ざる)+を得ない",ex:"事情があり参加せざるを得ない。",exT:"Sharoit bor, qatnashmasdan iloji yo'q.",sim:["～しかない-boshqa iloj yo'q","～ないわけにはいかない-ijtimoiy"],tip:"ざるを得ない=rasmiy MAJBURIYAT, しかない=boshqa variant yo'q",we:[{w:"食べざるを得ない→する例外:せざるを得ない",y:"する→せざるを得ない (maxsus qoida)"}],cat:"d7"},
{id:"db6",g:"～っぱなし",mn:"...qilgancha qoldirib qo'yish",mj:"～したまま放置する",st:"ます形+っぱなし",ex:"テレビをつけっぱなしで寝てしまった。",exT:"Televizorni yoqilgan holda uxlab qoldim.",sim:["～たまま-holda","～きり-keyin qaytmay"],tip:"っぱなし=SALBIY放置(qo'yib ketish), たまま=neytral holat",we:[{w:"ドアが開きっぱなしだ",y:"自動詞 ham mumkin: 開く→開きっぱなし. 他動詞: 開ける→開けっぱなし"}],cat:"d8"},
{id:"db7",g:"～次第",mn:"...shi bilanoq / ...ga bog'liq",mj:"～したらすぐ/～によって決まる",st:"ます形+次第(すぐ)/名詞+次第(依存)",ex:"届き次第ご連絡します。",exT:"Yetib kelishi bilanoq xabar beraman.",sim:["～たらすぐ-oddiy","～によって-...ga qarab"],tip:"V+次第=bilanoq(tezlik). N+次第=bog'liq(nima-dir hal qiladi)",we:[{w:"天気次第で出かける",y:"N+次第='bog'liq'. 届き次第='bilanoq'. IKKI grammatika!"}],cat:"d8"},
{id:"db8",g:"～に限らず",mn:"...ga cheklanmay",mj:"～だけでなく広く",st:"名詞+に限らず",ex:"学生に限らず社会人も参加できる。",exT:"Faqat talabalar emas, ishchilar ham qatnashishi mumkin.",sim:["～だけでなく-nafaqat","～ばかりでなく-nafaqat"],tip:"に限らず=chegarasiz KENG(rasmiy), だけでなく=oddiy nafaqat",we:[{w:"彼に限らず優しい",y:"XATO! Doira kengaytirish kerak: 彼に限らず皆優しい"}],cat:"d8"},
{id:"db9",g:"～からには",mn:"...ekan, albatta",mj:"～以上は当然～すべき",st:"普通形+からには",ex:"約束したからには必ず守る。",exT:"Va'da bergan ekan, albatta bajaraman.",sim:["～以上-rasmiy","～上は-rasmiy"],tip:"からには=shaxsiy qat'iy IRODA, 以上=rasmiy majburiyat",we:[{w:"雨が降るからには傘を持つ",y:"からには=IRODA/mas'uliyat kerak. Bu oddiy shart→から/ので"}],cat:"d8"},
{id:"db10",g:"～とは限らない",mn:"...deb bo'lmaydi, har doim emas",mj:"必ずしも～ではない",st:"普通形+とは限らない",ex:"高いものがいいとは限らない。",exT:"Qimmat narsa yaxshi deb bo'lmaydi.",sim:["～わけではない-shunday degani emas","～ないことはない-mumkin emas emas"],tip:"とは限らない=UMUMIY fikrga QARSHI(har doim emas), わけではない=qisman inkor",we:[{w:"彼が来ないとは限らない",y:"=kelmasligi aniq emas=kelishi mumkin. To'g'ri ishlatilish!"}],cat:"d8"},
{id:"db11",g:"～にわたって",mn:"...davomida, ...bo'ylab",mj:"広い範囲・長い期間に及んで",st:"名詞+にわたって",ex:"三日間にわたって会議が行われた。",exT:"Uch kun davomida yig'ilish o'tkazildi.",sim:["～を通じて-orqali/davomida","～にかけて-gacha"],tip:"にわたって=BUTUN davr/maydon, を通じて=orqali+davomida",we:[{w:"月曜にわたって会議する",y:"XATO! Bir kun uchun emas. KENG davr: 月曜から金曜にわたって"}],cat:"d9"},
{id:"db12",g:"～たところ",mn:"...ganda (natija kutilmagan)",mj:"～したら意外な結果",st:"た形+ところ",ex:"調べたところ原因がわかった。",exT:"Tekshirganimda sababi aniqlandi.",sim:["～たら-oddiy shart","～てみたら-ko'rganda"],tip:"たところ=kutilmagan/yangi NATIJA topildi, たら=oddiy shart",we:[{w:"食べたところ美味しかった",y:"たところ=aniqlash/TOPISH uchun yaxshi. His-tuyg'u uchun てみたら yaxshi"}],cat:"d9"},
{id:"db13",g:"～にしろ～にしろ",mn:"...bo'lsin ...bo'lsin",mj:"どちらの場合でも",st:"名詞/普通形+にしろ～にしろ",ex:"賛成にしろ反対にしろ理由を述べてください。",exT:"Qo'llang yoki qarshi bo'ling, sabab ayting.",sim:["～にせよ～にせよ-rasmiy","～であれ～であれ-juda rasmiy"],tip:"にしろにしろ=har ikkala holda HAM(oddiy), にせよ=rasmiy",we:[{w:"行くにしろ楽しい",y:"XATO! IKKITA variant kerak: 行くにしろ行かないにしろ楽しもう"}],cat:"d9"},
{id:"db14",g:"～向け",mn:"...uchun mo'ljallangan",mj:"～を対象に作られた",st:"名詞+向け/向けの+名詞",ex:"子供向けの番組が人気だ。",exT:"Bolalar uchun dastur mashhur.",sim:["～用-texnik ishlatish","～向き-mos keladi"],tip:"向け=MAQSADLI auditoriya, 用=texnik maqsad, 向き=tabiatdan mos",we:[{w:"この靴は走る向けだ",y:"Texnik maqsad=用: ランニング用. 向け=odam guruhi: 初心者向け"}],cat:"d9"},
{id:"db15",g:"～おそれがある",mn:"...xavfi bor",mj:"～かもしれない（悪いこと）",st:"辞書形/名詞の+おそれがある",ex:"台風で被害が出るおそれがある。",exT:"Bo'ron tufayli zarar yetish xavfi bor.",sim:["～かねない-ogohlantirish","～かもしれない-neytral"],tip:"おそれがある=RASMIY xavf(yangilik/hisobot), かねない=shaxsiy ogohlantirish",we:[{w:"合格するおそれがある",y:"XATO! Faqat SALBIY natija uchun. Ijobiy uchun 可能性がある"}],cat:"d9"},
{id:"db16",g:"～にあたって",mn:"...munosabati bilan, ...da",mj:"～する重要な時に",st:"辞書形/名詞+にあたって",ex:"入学にあたって必要な書類を準備した。",exT:"O'qishga kirish munosabati bilan hujjatlar tayyorladim.",sim:["～に際して-rasmiy paytda","～上で-uchun"],tip:"にあたって=MUHIM lahza/boshlanish, に際して=rasmiy payt, 上で=shart",we:[{w:"ご飯を食べるにあたって手を洗う",y:"Kundalik ish uchun emas. MUHIM voqea uchun: 卒業にあたって"}],cat:"d9"}
];


// Dec Dokkai - 6 ta
const DD=[
{id:"dd1",t:"短文-ストレス管理",p:"現代社会においてストレスは避けられないものとなっている。長期間のストレスは心身に悪影響を及ぼし、うつ病や生活習慣病の原因にもなり得る。専門家は適度な運動、十分な睡眠、趣味の時間確保を推奨している。また、完璧主義をやめ、自分の限界を認めることも重要だとされている。ストレスをゼロにすることは不可能だが、上手に付き合う方法を身につけることが大切である。",qs:[{q:"筆者が最も伝えたいことは？",o:["ストレスは完全になくすべき","ストレスと上手に付き合う方法が大切","運動だけでストレスは解消できる","完璧主義が一番の原因"],c:1,e:"'上手に付き合う方法を身につけることが大切'と結論",wr:["'ゼロにすることは不可能'と述べているので逆","運動は推奨の一つで'だけ'とは書いていない","原因の一つだが'一番'とは述べていない"]}],kv:["心身-tan va ruh","及ぼす-ta'sir qilmoq","推奨-tavsiya","完璧主義-perfektsionizm"],cat:"short"},
{id:"dd2",t:"短文-高齢化社会",p:"日本は世界で最も高齢化が進んだ国の一つである。65歳以上の人口が全体の約29%を占めている。労働力不足、社会保障費の増大、地方の過疎化など課題は山積している。政府は定年延長や外国人労働者の受け入れ拡大などの対策を講じているが、根本的な解決には出生率の回復が不可欠とされている。高齢者が活躍できる社会づくりも同時に求められている。",qs:[{q:"高齢化の課題として述べられていないものは？",o:["労働力不足","社会保障費増大","教育水準の低下","地方の過疎化"],c:2,e:"教育水準の低下は本文に言及なし",wr:["文中に課題として明記","文中に課題として明記","文中に課題として明記"]}],kv:["高齢化-keksayish","過疎化-aholi kamayishi","出生率-tug'ilish darajasi","不可欠-zarur"],cat:"short"},
{id:"dd3",t:"中文-コミュニケーション",p:"SNSの普及により人々のコミュニケーション方法は大きく変化した。短いメッセージやスタンプで感情を伝えることが一般的になり、便利さが増した反面、誤解が生じやすくなっている。特にテキストでは声のトーンや表情が伝わらないため、冗談が怒りと受け取られることもある。対面でのコミュニケーション能力の低下を指摘する声もある。しかしSNSには離れた人と繋がれるという大きな利点もあり、使い方次第で関係を深めることも可能である。",qs:[{q:"SNSコミュニケーションの問題点は？",o:["費用がかかる","誤解が生じやすい","返事が遅い","友達が減る"],c:1,e:"'誤解が生じやすくなっている'と明記",wr:["費用については触れていない","返事の速度は述べていない","友達減少は述べていない"]},{q:"筆者のSNSへの立場は？",o:["完全に否定","完全に肯定","利点と欠点の両方を認めている","無関心"],c:2,e:"問題点を挙げつつ'大きな利点'もあり'使い方次第'と述べている",wr:["利点も認めているので完全否定ではない","問題点も指摘しているので完全肯定ではない","積極的に論じているので無関心ではない"]}],kv:["普及-tarqalish","誤解-noto'g'ri tushunish","対面-yuzma-yuz","利点-afzallik"],cat:"medium"},
{id:"dd4",t:"中文-睡眠の重要性",p:"睡眠は健康の基盤であるにもかかわらず、日本人の平均睡眠時間は世界的に見ても短い。厚生労働省の調査では成人の約4割が6時間未満しか眠れていない。睡眠不足は集中力低下、免疫機能の低下、肥満リスクの増加など様々な問題を引き起こす。質の良い睡眠のためには就寝前のスマートフォン使用を控え、規則正しい生活リズムを維持することが推奨されている。",qs:[{q:"日本人の睡眠について正しいのは？",o:["世界平均より長い","約4割が6時間未満","8時間以上寝ている","特に問題はない"],c:1,e:"'成人の約4割が6時間未満'と明記",wr:["'世界的に見ても短い'と述べている","4割が6時間未満=8時間以上ではない","様々な問題を述べている"]},{q:"質の良い睡眠のために勧められていないのは？",o:["スマホ使用を控える","規則正しい生活","激しい運動をする","生活リズム維持"],c:2,e:"激しい運動は本文に述べられていない",wr:["文中に推奨として明記","文中に推奨として明記","'規則正しい生活リズムを維持'と同義"]}],kv:["基盤-asos","免疫-immunitet","肥満-semirish","維持-saqlab turish"],cat:"medium"},
{id:"dd5",t:"長文-地方活性化",p:"日本各地で地方活性化の取り組みが行われている。特に注目されているのが「ふるさと納税」制度だ。都市部の住民が地方自治体に寄付をすることで返礼品を受け取れるこの制度は、地方の特産品の認知度向上に貢献している。また、テレワークの普及により都市から地方への移住者が増加している。地方は豊かな自然環境や低い住居費が魅力だが、医療機関や教育機関の不足が課題となっている。持続可能な地域社会の実現には、デジタル技術の活用と住民参加のまちづくりが鍵を握る。",qs:[{q:"ふるさと納税の効果として述べられているのは？",o:["地方の人口増加","特産品の認知度向上","医療機関の整備","教育機関の増加"],c:1,e:"'地方の特産品の認知度向上に貢献'と明記",wr:["人口増加はテレワーク移住の話","医療は課題であり納税の効果ではない","教育は課題であり納税の効果ではない"]},{q:"地方移住の課題は？",o:["自然環境がない","住居費が高い","医療・教育機関の不足","仕事がまったくない"],c:2,e:"'医療機関や教育機関の不足が課題'と明記",wr:["'豊かな自然環境'は魅力として述べている","'低い住居費'は魅力として述べている","テレワークでの仕事は可能と示唆されている"]}],kv:["活性化-jonlantirish","寄付-xayriya","返礼品-javob sovg'a","持続可能-barqaror"],cat:"long"},
{id:"dd6",t:"情報検索-セミナー案内",p:"ビジネスマナーセミナー\\n日時：2024年1月20日（土）13:00～17:00\\n場所：中央公民館3階会議室\\n対象：新入社員・内定者（社会人経験3年未満の方も可）\\n定員：30名（先着順）\\n参加費：2,000円（テキスト代込み）\\n申込：メールまたはFAXで1月15日まで\\n持ち物：筆記用具\\n※当日は名刺交換の練習があります。名刺をお持ちの方はご持参ください。",qs:[{q:"参加できるのは？",o:["社会人経験5年の人","新入社員","学生なら誰でも","定年退職者"],c:1,e:"対象は'新入社員・内定者・経験3年未満'",wr:["3年未満が条件なので5年は対象外","学生全般ではなく内定者限定","定年退職者は対象外"]},{q:"名刺について正しいのは？",o:["全員持参が必須","持っている人だけ持参","会場で作れる","不要"],c:1,e:"'お持ちの方はご持参ください'=持っている人だけ",wr:["'お持ちの方は'なので全員必須ではない","会場で作れるとは書いていない","名刺交換練習があるので不要ではない"]}],kv:["先着順-kelish tartibida","内定者-ishga tayinlangan","公民館-jamoat markazi","持参-olib kelish"],cat:"joho"}
];


// Dokkai Vocab - 32 ta (Dec passages)
const DV=[
{id:"dv1",k:"避ける",r:"さける",mn:"qochmoq, yiroq turmoq",mj:"近づかないようにする",lv:"N2",src:"d-dk-1",sim:["逃れる-qochib qutulish"],tip:"避ける=ataylab yiroq turish, 逃れる=xavfdan qochish",cat:"dvoc"},
{id:"dv2",k:"悪影響",r:"あくえいきょう",mn:"yomon ta'sir",mj:"悪い影響",lv:"N2",src:"d-dk-1",sim:["害-zarar"],tip:"悪影響=noaniq salbiy ta'sir, 害=aniq zarar",cat:"dvoc"},
{id:"dv3",k:"適度",r:"てきど",mn:"me'yorida, o'rtacha",mj:"ちょうどよい程度",lv:"N2",src:"d-dk-1",sim:["程よい-o'rtacha"],tip:"適度=ilmiy/rasmiy, 程よい=kundalik",cat:"dvoc"},
{id:"dv4",k:"付き合う",r:"つきあう",mn:"munosabat qilmoq",mj:"人と交際する、相手をする",lv:"N2",src:"d-dk-1",sim:["交際する-rasmiy munosabat"],tip:"付き合う=umumiy aloqa, 交際する=rasmiy/romantik",cat:"dvoc"},
{id:"dv5",k:"占める",r:"しめる",mn:"egallamoq, tashkil etmoq",mj:"割合を持つ",lv:"N2",src:"d-dk-2",sim:["構成する-tuzmoq"],tip:"占める=%/ulush uchun, 構成する=tarkib uchun",cat:"dvoc"},
{id:"dv6",k:"山積",r:"さんせき",mn:"ko'p to'planish",mj:"問題が多くたまること",lv:"N1",src:"d-dk-2",sim:["堆積-jismoniy to'planish"],tip:"山積=muammo/ish, 堆積=fizik moddiy",cat:"dvoc"},
{id:"dv7",k:"講じる",r:"こうじる",mn:"choralar ko'rmoq",mj:"対策を行う",lv:"N1",src:"d-dk-2",sim:["施す-amalga oshirish"],tip:"講じる=rasmiy choralar, 施す=xayriya/tibbiy",cat:"dvoc"},
{id:"dv8",k:"根本的",r:"こんぽんてき",mn:"tubdan, asosiy",mj:"物事の根元にかかわる",st:"",lv:"N1",src:"d-dk-2",sim:["抜本的-tubdan o'zgartirish"],tip:"根本的=asos/ildiz, 抜本的=ildizidan qo'porish(kuchli)",cat:"dvoc"},
{id:"dv9",k:"普及",r:"ふきゅう",mn:"tarqalish, keng yoyilish",mj:"広く行き渡ること",lv:"N2",src:"d-dk-3",sim:["浸透-singish"],tip:"普及=texnologiya/bilim tarqalishi, 浸透=g'oya/madaniyat singishi",cat:"dvoc"},
{id:"dv10",k:"誤解",r:"ごかい",mn:"noto'g'ri tushunish",mj:"意味を取り違えること",lv:"N2",src:"d-dk-3",sim:["曲解-ataylab buzish"],tip:"誤解=tasodifiy xato, 曲解=ataylab noto'g'ri",cat:"dvoc"},
{id:"dv11",k:"対面",r:"たいめん",mn:"yuzma-yuz",mj:"直接会うこと",lv:"N2",src:"d-dk-3",sim:["面と向かって-to'g'ridan-to'g'ri"],tip:"対面=neytral, 面と向かって=jasurona to'g'ridan",cat:"dvoc"},
{id:"dv12",k:"基盤",r:"きばん",mn:"asos, poydevor",mj:"土台となるもの",lv:"N1",src:"d-dk-4",sim:["基礎-asos","土台-poydevor"],tip:"基盤=tizim/jamiyat asosi, 基礎=boshlang'ich, 土台=jismoniy",cat:"dvoc"},
{id:"dv13",k:"免疫",r:"めんえき",mn:"immunitet",mj:"病気から体を守る力",lv:"N1",src:"d-dk-4",sim:["抵抗力-qarshilik kuchi"],tip:"免疫=tibbiy termin, 抵抗力=umumiy",cat:"dvoc"},
{id:"dv14",k:"肥満",r:"ひまん",mn:"semirish",mj:"太りすぎの状態",lv:"N2",src:"d-dk-4",sim:["太る-semirmoq"],tip:"肥満=tibbiy holat/kasallik, 太る=oddiy fe'l",cat:"dvoc"},
{id:"dv15",k:"維持",r:"いじ",mn:"saqlab turish",mj:"同じ状態を保つこと",lv:"N2",src:"d-dk-4",sim:["保つ-saqlamoq","持続-davom ettirish"],tip:"維持=aniq holat saqlash, 保つ=umumiy, 持続=uzluksiz davom",cat:"dvoc"},
{id:"dv16",k:"活性化",r:"かっせいか",mn:"jonlantirish",mj:"活発にすること",lv:"N1",src:"d-dk-5",sim:["振興-rivojlantirish"],tip:"活性化=susaygan narsani jonlantirish, 振興=yangi rivojlantirish",cat:"dvoc"},
{id:"dv17",k:"寄付",r:"きふ",mn:"xayriya, ehson",mj:"お金や物を贈ること",lv:"N2",src:"d-dk-5",sim:["寄贈-moddiy sovg'a","献金-pul xayriya"],tip:"寄付=umumiy, 寄贈=kitob/buyum, 献金=faqat pul",cat:"dvoc"},
{id:"dv18",k:"認知度",r:"にんちど",mn:"tanilganlik darajasi",mj:"知られている程度",lv:"N1",src:"d-dk-5",sim:["知名度-mashhurlik"],tip:"認知度=mahsulot/tushuncha, 知名度=odam/joy",cat:"dvoc"},
{id:"dv19",k:"移住",r:"いじゅう",mn:"ko'chib o'tish",mj:"別の場所に住むこと",lv:"N2",src:"d-dk-5",sim:["引っ越し-ko'chish","転居-rasmiy ko'chish"],tip:"移住=boshqa shahar/mamlakat, 引っ越し=kundalik, 転居=rasmiy hujjat",cat:"dvoc"},
{id:"dv20",k:"持続可能",r:"じぞくかのう",mn:"barqaror, davomli",mj:"長く続けられる",lv:"N1",src:"d-dk-5",sim:["永続的-abadiy"],tip:"持続可能=SDGs/ekologiya, 永続的=abadiy(ideal)",cat:"dvoc"},
{id:"dv21",k:"先着順",r:"せんちゃくじゅん",mn:"kelish tartibida",mj:"早く来た人から順に",lv:"N2",src:"d-dk-6",sim:["抽選-lotereya"],tip:"先着順=tezroq kelgan yutadi, 抽選=tasodifiy tanlash",cat:"dvoc"},
{id:"dv22",k:"内定",r:"ないてい",mn:"ishga tayinlanish (rasmiy emas)",mj:"正式前に決まること",lv:"N1",src:"d-dk-6",sim:["採用-rasmiy qabul"],tip:"内定=og'zaki kelishuv, 採用=rasmiy ishga olish",cat:"dvoc"},
{id:"dv23",k:"心身",r:"しんしん",mn:"tan va ruh",mj:"心と体",lv:"N2",src:"d-dk-1",sim:["精神-ruh","肉体-jism"],tip:"心身=ikkalasi birga, 精神=faqat ruhiy, 肉体=faqat jismoniy",cat:"dvoc"},
{id:"dv24",k:"推奨",r:"すいしょう",mn:"tavsiya qilish (rasmiy)",mj:"すすめること",lv:"N1",src:"d-dk-1",sim:["勧める-tavsiya(oddiy)"],tip:"推奨=rasmiy/ekspert tavsiyasi, 勧める=oddiy kundalik",cat:"dvoc"},
{id:"dv25",k:"社会保障",r:"しゃかいほしょう",mn:"ijtimoiy ta'minot",mj:"国民の生活を守る制度",lv:"N1",src:"d-dk-2",sim:["福祉-farovonlik"],tip:"社会保障=davlat tizimi(pension/sug'urta), 福祉=xizmatlar",cat:"dvoc"},
{id:"dv26",k:"就寝",r:"しゅうしん",mn:"uxlashga yotish",mj:"寝ること",lv:"N2",src:"d-dk-4",sim:["睡眠-uyqu"],tip:"就寝=yotish HARAKATI, 睡眠=uyqu HOLATI",cat:"dvoc"},
{id:"dv27",k:"指摘",r:"してき",mn:"ko'rsatib berish",mj:"問題点などを示すこと",lv:"N2",src:"d-dk-3",sim:["批判-tanqid"],tip:"指摘=neytral/foydali ko'rsatish, 批判=salbiy tanqid",cat:"dvoc"},
{id:"dv28",k:"繋がる",r:"つながる",mn:"bog'lanmoq, aloqada bo'lmoq",mj:"関係が続くこと",lv:"N2",src:"d-dk-3",sim:["結びつく-bog'lanmoq"],tip:"繋がる=davomiy aloqa, 結びつく=yangi bog'lanish",cat:"dvoc"},
{id:"dv29",k:"返礼品",r:"へんれいひん",mn:"javob sovg'a",mj:"お礼として贈る品物",lv:"N1",src:"d-dk-5",sim:["お返し-javob sovg'a(oddiy)"],tip:"返礼品=rasmiy/furusato, お返し=kundalik",cat:"dvoc"},
{id:"dv30",k:"過疎化",r:"かそか",mn:"aholi kamayishi",mj:"人口が減って寂れること",lv:"N1",src:"d-dk-2",sim:["人口減少-aholi kamayishi"],tip:"過疎化=hududiy muammo(qishloq), 人口減少=statistik fakt",cat:"dvoc"},
{id:"dv31",k:"出生率",r:"しゅっしょうりつ",mn:"tug'ilish darajasi",mj:"生まれる子供の割合",lv:"N1",src:"d-dk-2",sim:["少子化-kam farzandlilik"],tip:"出生率=statistik raqam, 少子化=ijtimoiy muammo",cat:"dvoc"},
{id:"dv32",k:"集中力",r:"しゅうちゅうりょく",mn:"diqqat kuchi",mj:"一つのことに注意を向ける力",lv:"N2",src:"d-dk-4",sim:["注意力-e'tibor"],tip:"集中力=chuqur fokus, 注意力=umumiy diqqat",cat:"dvoc"}
];
