// JLPT N2 2023年7月 - Flashcard Data
// Manba: JLPT N2 2023 July PDF

const flashcardData = [
  // === 語彙 (GOI) ===
  { type: "goi", front: "運賃", reading: "うんちん", meaning: "Yo'l haqi / Transport narxi", example: "バスの運賃を払う。", exampleUz: "Avtobus yo'l haqini to'lamoq." },
  { type: "goi", front: "乱れる", reading: "みだれる", meaning: "Tartibsizlanmoq / To'zg'imoq", example: "風が強くて、髪が乱れてしまった。", exampleUz: "Shamol kuchli bo'lib, soch to'zg'ib ketdi." },
  { type: "goi", front: "模範", reading: "もはん", meaning: "Namuna / O'rnak", example: "正しい泳ぎ方の模範を示した。", exampleUz: "To'g'ri suzish usulining namunasini ko'rsatdi." },
  { type: "goi", front: "険しい", reading: "けわしい", meaning: "Tik / Qiyalik / Qattiq", example: "思った以上に険しかった。", exampleUz: "O'ylagandan ham tikroq edi." },
  { type: "goi", front: "握手", reading: "あくしゅ", meaning: "Qo'l siqish", example: "さっき握手していた人は誰ですか。", exampleUz: "Hozirgina qo'l siqishgan odam kim?" },
  { type: "goi", front: "布", reading: "ぬの", meaning: "Mato / Gazlama", example: "その布を広げてください。", exampleUz: "O'sha matoni yoying." },
  { type: "goi", front: "福祉", reading: "ふくし", meaning: "Ijtimoiy ta'minot / Farovonlik", example: "今後は福祉の仕事に就く予定です。", exampleUz: "Bundan keyin ijtimoiy ta'minot ishiga kirishni rejalashtirmoqdaman." },
  { type: "goi", front: "捨てる", reading: "すてる", meaning: "Tashlamoq / Chiqarib tashlamoq", example: "毎日たくさんのごみが捨てられている。", exampleUz: "Har kuni ko'p axlat tashlanmoqda." },
  { type: "goi", front: "機嫌", reading: "きげん", meaning: "Kayfiyat / Ko'ngil", example: "機嫌がよいときに頼んでみよう。", exampleUz: "Kayfiyati yaxshi paytda iltimos qilib ko'raylik." },
  { type: "goi", front: "損失", reading: "そんしつ", meaning: "Zarar / Yo'qotish", example: "会社にとって大きな損失だ。", exampleUz: "Kompaniya uchun katta zarar." },
  { type: "goi", front: "誤解", reading: "ごかい", meaning: "Noto'g'ri tushunish", example: "冷たい人だとよく誤解される。", exampleUz: "Ko'pincha sovuq odam deb noto'g'ri tushuniladi." },
  { type: "goi", front: "好調", reading: "こうちょう", meaning: "Yaxshi holat / Muvaffaqiyatli", example: "売れ行きが好調なので生産量を増やす。", exampleUz: "Sotilishi yaxshi bo'lgani uchun ishlab chiqarishni oshiramiz." },
  { type: "goi", front: "頼もしい", reading: "たのもしい", meaning: "Ishonchli / Tayanchli", example: "本当に頼もしい部下だと思う。", exampleUz: "Chindan ham ishonchli xodim deb o'ylayman." },
  { type: "goi", front: "節約", reading: "せつやく", meaning: "Tejash / Iqtisod qilish", example: "食費を節約するために外食をしない。", exampleUz: "Ovqat xarajatini tejash uchun tashqarida ovqatlanmaslik." },
  { type: "goi", front: "飛びつく", reading: "とびつく", meaning: "Darhol tashlanmoq / Qabul qilmoq", example: "簡単にお金がもうかる話にすぐ飛びつくな。", exampleUz: "Oson pul topish gapiga darhol tashlanma." },
  { type: "goi", front: "求人", reading: "きゅうじん", meaning: "Ish e'loni / Xodim izlash", example: "求人があったので早速応募した。", exampleUz: "Ish e'loni bor edi, darhol ariza berdim." },
  { type: "goi", front: "惜しい", reading: "おしい", meaning: "Afsuslanarli / Qadrli (もったいない)", example: "この建物を壊すには惜しい。", exampleUz: "Bu binoni buzish afsus." },
  { type: "goi", front: "油断", reading: "ゆだん", meaning: "Beparvolik / E'tiborsizlik", example: "あのときは油断していた。", exampleUz: "O'sha paytda e'tiborsiz edim." },
  { type: "goi", front: "早期", reading: "そうき", meaning: "Erta bosqich / Dastlabki davr", example: "病気を早期の段階で見つける。", exampleUz: "Kasallikni erta bosqichda aniqlash." },
  { type: "goi", front: "偉大", reading: "いだい", meaning: "Buyuk / Ulug'vor", example: "この国には偉大な画家がたくさんいる。", exampleUz: "Bu mamlakatda buyuk rassamlar ko'p." },
  { type: "goi", front: "印", reading: "しるし", meaning: "Belgi / Nishon", example: "大切な単語に赤のペンで印をつけた。", exampleUz: "Muhim so'zlarga qizil qalam bilan belgi qo'ydim." },
  { type: "goi", front: "続出", reading: "ぞくしゅつ", meaning: "Ketma-ket chiqish", example: "転んでけがをする人が続出している。", exampleUz: "Yiqilib jarohat oluvchilar ketma-ket chiqmoqda." },
  { type: "goi", front: "妨げる", reading: "さまたげる", meaning: "To'sqinlik qilmoq / Halaqit bermoq", example: "会議の進行をさまたげないでください。", exampleUz: "Yig'ilish jarayoniga halaqit bermang." },
  { type: "goi", front: "避難訓練", reading: "ひなんくんれん", meaning: "Evakuatsiya mashqi", example: "学校では定期的に避難訓練が行われる。", exampleUz: "Maktablarda muntazam evakuatsiya mashqlari o'tkaziladi." },
  { type: "goi", front: "睡眠", reading: "すいみん", meaning: "Uyqu", example: "睡眠には疲労をとる効果がある。", exampleUz: "Uyqu charchoqni olib tashlash samarasiga ega." },
  { type: "goi", front: "疲労", reading: "ひろう", meaning: "Charchoq / Holsizlik", example: "体にたまった疲労をとる。", exampleUz: "Tanada to'plangan charchoqni olib tashlash." },
  { type: "goi", front: "繊細", reading: "せんさい", meaning: "Nozik / Nafis / Sezgir", example: "繊細な香りを味わう。", exampleUz: "Nozik hidni tatib ko'rish." },
  { type: "goi", front: "貴重", reading: "きちょう", meaning: "Qadrli / Qimmatbaho / Nodir", example: "人工的に生産できないため大変貴重だ。", exampleUz: "Sun'iy ishlab chiqarib bo'lmagani uchun juda qadrli." },
  { type: "goi", front: "需要", reading: "じゅよう", meaning: "Talab / Ehtiyoj", example: "需要が増えすぎればなくなるおそれもある。", exampleUz: "Talab ortsa, yo'qolib ketish xavfi ham bor." },
  { type: "goi", front: "鑑賞", reading: "かんしょう", meaning: "Baholash / Zavqlanib ko'rish", example: "古典文学を鑑賞する。", exampleUz: "Klassik adabiyotni zavqlanib o'qimoq." },
  { type: "goi", front: "穏やか", reading: "おだやか", meaning: "Tinch / Sokin / Xotirjam", example: "穏やかな気持ちで過ごす。", exampleUz: "Tinch kayfiyatda vaqt o'tkazmoq." },
  { type: "goi", front: "競争", reading: "きょうそう", meaning: "Raqobat / Musobaqa", example: "生物は競争で環境を見つける。", exampleUz: "Jonzotlar raqobat orqali muhitni topadi." },
  { type: "goi", front: "排除", reading: "はいじょ", meaning: "Chetlashtirish / Olib tashlash", example: "競争は敗者を排除するプロセスではない。", exampleUz: "Raqobat mag'lublarni chetlashtirish emas." },
  { type: "goi", front: "抗議", reading: "こうぎ", meaning: "Norozilik / E'tiroz", example: "抗議の声をあげる。", exampleUz: "Norozilik ovozini ko'tarmoq." },
  { type: "goi", front: "挑戦", reading: "ちょうせん", meaning: "Qiyinchilikka bardosh / Challenge", example: "宇宙飛行への挑戦を決心した。", exampleUz: "Kosmik parvozga challenje qilishga qaror qildi." },
  { type: "goi", front: "緊張", reading: "きんちょう", meaning: "Zo'riqish / Hayajonlanish", example: "緊張感のある生活を送りたい。", exampleUz: "Hayajonli hayot yashagim keladi." },
  { type: "goi", front: "配慮", reading: "はいりょ", meaning: "E'tibor / G'amxo'rlik", example: "配慮と訓練が必要だ。", exampleUz: "E'tibor va mashq kerak." },
  { type: "goi", front: "意欲", reading: "いよく", meaning: "Ishtiyoq / Istak / Rag'bat", example: "仕事を理解しようという意欲を失う。", exampleUz: "Ishni tushunish ishtiyoqini yo'qotish." },
  { type: "goi", front: "実践", reading: "じっせん", meaning: "Amalda qo'llash / Tatbiq etish", example: "私が実践しているのは内容を絞ることだ。", exampleUz: "Men amalda qo'llayotgan narsa - mazmunni cheklab berish." },
  { type: "goi", front: "漠然", reading: "ばくぜん", meaning: "Noaniq / Loyqa / Aniq emas", example: "漠然とした認識しか持てなかった。", exampleUz: "Faqat noaniq tushunchaga ega edim." },

  // === 漢字 (KANJI) ===
  { type: "kanji", front: "乱", reading: "ラン / みだ.れる", meaning: "Tartibsizlik / Buzilish", example: "混乱（こんらん）・乱れる（みだれる）", exampleUz: "On: RAN / Kun: midareru" },
  { type: "kanji", front: "模", reading: "モ・ボ", meaning: "Namuna / Nusxa", example: "模範（もはん）・模様（もよう）・規模（きぼ）", exampleUz: "On: MO, BO" },
  { type: "kanji", front: "険", reading: "ケン / けわ.しい", meaning: "Tik / Xavfli", example: "危険（きけん）・保険（ほけん）・険しい", exampleUz: "On: KEN / Kun: kewashii" },
  { type: "kanji", front: "握", reading: "アク / にぎ.る", meaning: "Ushlamoq / Siqmoq", example: "握手（あくしゅ）・把握（はあく）", exampleUz: "On: AKU / Kun: nigiru" },
  { type: "kanji", front: "損", reading: "ソン / そこ.なう", meaning: "Zarar / Yo'qotish", example: "損失（そんしつ）・損害（そんがい）", exampleUz: "On: SON / Kun: sokonau" },
  { type: "kanji", front: "誤", reading: "ゴ / あやま.る", meaning: "Xato / Noto'g'ri", example: "誤解（ごかい）・錯誤（さくご）", exampleUz: "On: GO / Kun: ayamaru" },
  { type: "kanji", front: "節", reading: "セツ / ふし", meaning: "Bo'g'in / Tejash / Fasl", example: "節約（せつやく）・季節（きせつ）", exampleUz: "On: SETSU / Kun: fushi" },
  { type: "kanji", front: "繊", reading: "セン", meaning: "Nozik / Ingichka", example: "繊細（せんさい）・繊維（せんい）", exampleUz: "On: SEN" },
  { type: "kanji", front: "避", reading: "ヒ / さ.ける", meaning: "Qochish / Saqlanish", example: "避難（ひなん）・回避（かいひ）", exampleUz: "On: HI / Kun: sakeru" },
  { type: "kanji", front: "競", reading: "キョウ / きそ.う", meaning: "Raqobat / Musobaqa", example: "競争（きょうそう）・競技（きょうぎ）", exampleUz: "On: KYOU / Kun: kisou" },
  { type: "kanji", front: "抗", reading: "コウ", meaning: "Qarshilik / Qarshi turish", example: "抗議（こうぎ）・抵抗（ていこう）", exampleUz: "On: KOU" },
  { type: "kanji", front: "挑", reading: "チョウ / いど.む", meaning: "Challenje / Qo'zg'amoq", example: "挑戦（ちょうせん）・挑発（ちょうはつ）", exampleUz: "On: CHOU / Kun: idomu" },
  { type: "kanji", front: "鑑", reading: "カン / かがみ", meaning: "Ko'zgu / Baholamoq", example: "鑑賞（かんしょう）・鑑定（かんてい）", exampleUz: "On: KAN / Kun: kagami" },
  { type: "kanji", front: "維", reading: "イ", meaning: "Saqlamoq / Ip", example: "維持（いじ）・繊維（せんい）", exampleUz: "On: I" },
  { type: "kanji", front: "廊", reading: "ロウ", meaning: "Koridor / Yo'lak", example: "廊下（ろうか）・回廊（かいろう）", exampleUz: "On: ROU" },

  // === 文法 (BUNPO) ===
  { type: "bunpo", front: "～につれて", reading: "ni tsurete", meaning: "...ga qarab / ...bilan birga (o'zgarish)", example: "物語が進むにつれて心理が変化する。", exampleUz: "Hikoya davom etishi bilan ruhiyat o'zgaradi." },
  { type: "bunpo", front: "二度と～ない", reading: "nido to ~ nai", meaning: "Boshqa hech qachon ...mayman", example: "二度と行きたくない。", exampleUz: "Boshqa hech qachon bormayman." },
  { type: "bunpo", front: "～ものの", reading: "mono no", meaning: "...bo'lsa ham / ...ga qaramasdan", example: "メダルは獲得できなかったものの演技は素晴らしかった。", exampleUz: "Medal ololmasa ham ijro ajoyib edi." },
  { type: "bunpo", front: "～ばかりらしく", reading: "bakari rashiku", meaning: "Endigina ...ga o'xshab", example: "起きたばかりらしく、パジャマのままだった。", exampleUz: "Endigina turganga o'xshab, pijamada edi." },
  { type: "bunpo", front: "～というように", reading: "to iu you ni", meaning: "...degan tarzda / ...kabi ishlatiladi", example: "「リマインドした」というように使用される。", exampleUz: "'Remind qildim' kabi ishlatiladi." },
  { type: "bunpo", front: "～しておくことで", reading: "shite oku koto de", meaning: "...qilib qo'yish orqali", example: "訓練をしておくことで落ち着いて行動できる。", exampleUz: "Mashq qilib qo'yish orqali tinch harakat qilish mumkin." },
  { type: "bunpo", front: "～ぶり", reading: "buri", meaning: "...dan beri birinchi marta", example: "映画館は約５年ぶりだ。", exampleUz: "Kinoteatr taxminan 5 yildan beri birinchi." },
  { type: "bunpo", front: "～にほかならない", reading: "ni hoka naranai", meaning: "Boshqa narsa emas / Aynan ...dir", example: "機会を奪うことにほかならない。", exampleUz: "Aynan imkoniyatni tortib olish." },
  { type: "bunpo", front: "～とのことでした", reading: "to no koto deshita", meaning: "...degan gap edi (yetkazish)", example: "連絡してほしいとのことでした。", exampleUz: "Bog'laning degan gap edi." },
  { type: "bunpo", front: "～べきだった", reading: "beki datta", meaning: "...lishi kerak edi (afsus bilan)", example: "事前に確認しておくべきだった。", exampleUz: "Oldindan tekshirib qo'yishim kerak edi." },
  { type: "bunpo", front: "～ていただいたおかげ", reading: "te itadaita okage", meaning: "...qilib berganingiz tufayli", example: "応援していただいたおかげです。", exampleUz: "Qo'llab-quvvatlab berganingiz tufayli." },
  { type: "bunpo", front: "～にとっても", reading: "ni totte mo", meaning: "...uchun ham", example: "父にとっても趣味は始められる。", exampleUz: "Otam uchun ham hobbi boshlanishi mumkin." },
];
